# Generated by Django 4.2.6 on 2023-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankusers', '0002_alter_customuser_managers_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
