# Generated by Django 4.2.6 on 2023-11-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankusers', '0003_customuser_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
