# Generated by Django 4.2.6 on 2023-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='currentbalance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
